name: Test Downstream

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  downstream:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Test jupyterlab_server
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: jupyterlab_server

      - name: Test jupyterlab
        uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: jupyterlab
          package_spec: "\".[test]\""
          test_command: "python -m jupyterlab.browser_check --no-browser-test"

